version: 0.0
os: linux
files:
  - source: /index.html
    destination: /home/dbt-code

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 350
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
